import type { Metadata } from "next";
import Head from "next/head";
import { Poppins } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";

import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Handyman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <Head>
        <title>Handyman Canada - Your Trusted Handyman Service</title>
        <meta
          name="description"
          content="Professional handyman services in Canada. Reliable, affordable, and trusted by homeowners."
        />
        <meta
          name="keywords"
          content="handyman, Canada, home repair, maintenance, professional services"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body
        className={`${poppins.className} 'max-w-[1920px] bg-lightBG text-black`}
      >
        <div className="sticky z-10 top-0 left-0">
          <Header />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
