import type { Metadata } from 'next';
import Head from 'next/head';
import { Poppins } from 'next/font/google';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { ToastContainer, Slide } from 'react-toastify';
import SocialIcons from '@/components/socialIcons';
import Discount from '@/components/Discount';

import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

const structeData = {
  '@context': 'https://schema.org',
  '@type': 'LocalBusiness',
  name: 'HandyFriend',
  description:
    'HandyFriend is a reliable handyman service for all your home repair and maintenance needs.',
  image: 'logo.svg',
  logo: 'logo.svg',
  priceRange: '$',
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.5',
    reviewCount: '1560',
  },
  review: [
    {
      '@type': 'Review',
      author: 'John Doe',
      datePublished: '2024-07-01',
      description: 'Great service! Highly recommend HandyFriend for any home repairs.',
      name: 'Excellent Service',
      reviewRating: {
        '@type': 'Rating',
        ratingValue: '5',
      },
    },
    {
      '@type': 'Review',
      author: 'Jane Smith',
      datePublished: '2024-06-15',
      description: 'Professional and efficient. Will definitely use again.',
      name: 'Professional and Efficient',
      reviewRating: {
        '@type': 'Rating',
        ratingValue: '4',
      },
    },
  ],
  areaServed: {
    '@type': 'Place',
    name: [
      'Toronto & East York',
      'North York',
      'Scarborough',
      'Markham',
      'Richmond Hill',
      'Vaughan',
      'Etobicoke',
      'Mississauga',
      'Brampton',
    ],
  },
  makesOffer: {
    '@type': 'Offer',
    priceCurrency: 'CAD',
    price: 'Varies',
    url: 'https://handyfriend.ca',
  },
  address: {
    '@type': 'PostalAddress',
    addressCountry: 'Canada',
    addressLocality: [
      'Toronto & East York',
      'North York',
      'Scarborough',
      'Markham',
      'Richmond Hill',
      'Vaughan',
      'Etobicoke',
      'Mississauga',
      'Brampton',
    ],
  },
  url: 'https://handyfriend.ca',
  telephone: '+1-647-828-96-33',
};

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Handyman',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='scroll-smooth' lang='en'>
      <Head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta
          name='description'
          content='HandyFriend is a reliable handyman service based in Canada, offering a wide range of home repair and maintenance services. Our experienced professionals are dedicated to providing top-quality service to ensure your home is in perfect condition.'
        />
        <meta
          name='keywords'
          content='handyman, home repair, maintenance, HandyFriend, Canada, Toronto, East York, North York, Scarborough, Markham, Richmond Hill, Vaughan, Etobicoke, Mississauga, Brampton'
        />
        <meta name='author' content='HandyFriend' />
        <title>HandyFriend - Reliable Handyman Services in Canada</title>
        <script
          key='structured-1'
          type='application/ld+json'
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structeData) }}
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <body className={`${poppins.className} 'max-w-[1920px] bg-lightBG text-black`}>
        <ToastContainer
          className='z-[1000]'
          position='bottom-right'
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme='light'
          transition={Slide}
        />
        <div className='sticky z-10 top-0 left-0'>
          <Header />
        </div>
        {children}
        <Discount />
        <SocialIcons />
        <Footer />
      </body>
    </html>
  );
}
